### ISSUE TITLE
Paso 10: UI Drag\&Drop “Add Secret” para propietarios

### ISSUE THREAD

**Issue by gari01234** [gari01234/PRMTTN#21]
## Paso 10: UI Drag\&Drop “Add Secret” para propietarios

**Descripción general:**
Crear un área donde el dueño del NFT pueda arrastrar un archivo para cifrarlo y asociarlo al token.

<details>
<summary>Pasos detallados</summary>

1. **Crear rama** `feature/issue-10-dragdrop-secret`.

2. **Editar `index.html` – HTML**

   * Encuentra donde listan tus NFTs (“My Collection”).
   * Para cada token OWNED sin `secretCID`, inserta:

     ```html
     <div class="drop-area" data-token-id="${token.id}">
       Arrastra aquí tu archivo secreto
     </div>
     ```
   * *Tiempo:* \~10 min

3. **Editar `index.html` – CSS**

   * Al inicio, en `<style>` añade:

     ```css
     .drop-area {
       border: 2px dashed #888;
       padding: 1rem;
       margin: 0.5rem 0;
       text-align: center;
       cursor: pointer;
     }
     .drop-area.dragover { background: rgba(0,0,0,0.05); }
     ```
   * *Tiempo:* \~5 min

4. **Editar `index.html` – JS**

   * En tu `<script>`, tras todas las funciones, añade:

     ```js
     document.querySelectorAll(".drop-area").forEach(area => {
       area.addEventListener("dragover", e => { e.preventDefault(); area.classList.add("dragover"); });
       area.addEventListener("dragleave", () => area.classList.remove("dragover"));
       area.addEventListener("drop", async e => {
         e.preventDefault(); area.classList.remove("dragover");
         const file = e.dataTransfer.files[0];
         const sig = /* tu firma actual */;
         const key = await deriveKey(sig);
         const { cipherBuffer, iv } = await encryptFile(file, key);
         const secretCid = await uploadToBundlr(new Blob([cipherBuffer]));
         const metadataCid = await buildAndUploadMetadata(currentConfig, secretCid);
         await drop.erc721.update(area.dataset.tokenId, { secretCID: secretCid, iv });
         alert("Secret agregado!");
       });
     });
     ```
   * *Tiempo:* \~20 min

5. **Commit & PR**

   ```bash
   git add index.html
   git commit -m "Issue #10: Drag&Drop Add Secret UI"
   git push origin feature/issue-10-dragdrop-secret
   ```

</details>

* **Tiempo total:** 45 min
* **Prioridad:** Media
* **Dificultad:** Media–Alta
